### PR TITLE
ReactiveSocket: Remove `startAndWait` method

### PR DESCRIPTION
**Pull request by stevegury**
***Problem***
ReactiveSocket shouldn't have a public API encouraging usage of blocking code.

***Solution***
Remove the method, replace it by `start` where it was easy and
by `Unsafe.startAndWait` elsewhere.

### CODE REVIEW

**Comment by stevegury** [comment]
This needs to be merged after the removal of `reactivesocket-local-transport`

**Comment by NiteshKant** [comment]
@stevegury looks like removal of local transport (#142) is included in this PR, Otherwise it is 👍

**Comment by stevegury** [comment]
Yes, I'll merge master as soon as the removal of the local transport is merged.

**Comment by stevegury** [comment]
I added back local-transport.

**Pull request merged**
