### PR TITLE
Add hexstring tests for frame header encoding

### PR DESCRIPTION
**Pull request by yschimke**
Before vs After

```
         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 00 00 00 1a 00 01 00 20 00 00 00 00 00 00 00 00 |....... ........|
|00000010| 00 00 03 e8 00 00 00 00 00 00                   |..........      |
+--------+-------------------------------------------------+----------------+


         +-------------------------------------------------+
         |  0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f |
+--------+-------------------------------------------------+----------------+
|00000000| 00 00 00 1a 00 01 20 00 00 00 00 00 00 00 00 00 |...... .........|
|00000010| 00 00 03 e8 00 00 00 00 00 00                   |..........      |
+--------+-------------------------------------------------+----------------+
```

### CODE REVIEW

**Comment by yschimke** [comment]
Not sure what you think about unit testing the hex dump of the header bytes for frames?

```
    assertEquals(
        "0000003a000130000000000000000000000003e90000138d",
        ByteBufUtil.hexDump(encodedFrame.getByteBuffer().array(), 0, 24));
```

**Comment by stevegury** [comment]
I like the idea of unit-testing the hex dump: easy to spot and fix errors !

**Comment by stevegury** [comment]
👍 
If you don't mind, I propose to batch all breaking changes.
So let's keep the PR open for now.

**Comment by stevegury** [comment]
@yschimke could you merge master?

**Pull request merged**
