### PR TITLE
Tabs => Spaces

### PR DESCRIPTION
**Pull request by NiteshKant**
#### Problem

I don't agree with Richard Hendricks to use tabs over spaces.

#### Solution

Gimme back my spaces.

#### Result

Awesomeness .....

PS: I don't use vim or emacs... Idea rocks!

### CODE REVIEW

**Comment by tmontgomery** [comment]
For what it is worth, I am spaces >> tabs.

**Comment by stevegury** [comment]
Uniformity is more important than one choice or the other.

**Comment by yschimke** [comment]
+1 to uniformity.  I think it would be helpful if you bulk formatted the code according to a default Intellij settings as well.  Inconsistency of braces have been a grating on me :)

**Comment by NiteshKant** [comment]
@yschimke I thought to do that but may be we should agree on which formatting style to use first 😄

**Comment by yschimke** [comment]
Yep.  FWIW I find this sort of setup really easy to use https://github.com/square/java-code-styles/tree/master/configs

I'm not religious about styles, just want to be able to reformat code without thinking too much.  e.g. no standards for aligning javadoc params manually etc.

**Comment by stevegury** [comment]
If we all use IntelliJ, I propose to use the default Java code style.
AFAIK, it matches Sun/Oracle's recommended Java code style.

In `Editor > Code Style > Java > Scheme` choose `Default`

**Comment by NiteshKant** [comment]
I am fine with that so may be when the pending PRs are merged we can bulk reformat the code and remove warnings which are so annoying when reading the code.

**Comment by tmontgomery** [comment]
Uniformity is very good.

I have found that [Kevlin Henney's points](https://vimeo.com/74316116) make a lot of sense and are good guidelines for format, naming, etc. Also, good reasoning behind them.

**Pull request merged**
