### PR TITLE
Remove timeouts completely from ClientBuilder

### PR DESCRIPTION
**Pull request by rdegnan**

### CODE REVIEW

**Comment by NiteshKant** [comment]
👍 . @stevegury can you take a look?

**Comment by stevegury** [comment]
Please provide a minimal description of the motivations behind this PR.
Check the other PR for examples.

**Comment by NiteshKant** [comment]
@rdegnan I think we don't need this anymore, rite?

**Comment by stevegury** [comment]
I've merged most of that in #112 and the remaining will be in another PR.

**Comment by NiteshKant** [comment]
Ok I am closing this now.

**Pull request closed without merging**
