### PR TITLE
Extract interface `Availability`

### PR DESCRIPTION
**Pull request by NiteshKant**
#### Problem

`DuplexConnection`, `ReactiveSocket` and `ReactiveSocketClient` all provide a method `double availability()` and so can benefit from having a common interface.
This will be useful for giving event callbacks that retrieve availability as availability follows a pull model instead of push.

#### Modification

Added a new interface `AvailabilityProvider` and have the other interfaces extend it.

#### Result

Common way to access availabilty.

### CODE REVIEW

**Comment by NiteshKant** [comment]
\cc @stevegury

**Comment by NiteshKant** [comment]
`AvailabilitySupplier`?

**Comment by NiteshKant** [comment]
@stevegury should we merge for now (I need to move fwd with changes related to events) and revisit the name later?

**Comment by NiteshKant** [comment]
@stevegury I renamed `AvailabilityProvider` to `Availability`

**Comment by stevegury** [comment]
(For lack of a better word)

**Pull request merged**
